apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-of-life-app
  labels:
    app: game-of-life-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-of-life-app
  
# Pod template
  template:
    metadata:
      labels:
        app: game-of-life-app
    spec:
      containers:
        - name: game-of-life-app
          image: 645597104802.dkr.ecr.us-east-1.amazonaws.com/test-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
# Service template
apiVersion: v1
kind: Service
metadata:
  name: game-of-life-app
  labels:
    app: game-of-life-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
      app: game-of-life-app
